# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

parameters:
  - name: deployEnv
    type: object
    default:
      serviceConnection: 'my-azure-spn'
      environment: 'dev'
      region: 'eastus'
      environmentNumber: '01'

stages:
  - stage: DeployTerraform
    displayName: "Deploy Infra with Terraform"
    jobs:
      - template: pipelines/stages/terraform-deploy.yaml
        parameters:
          deployEnv: ${{ parameters.deployEnv }}
 
